rails-kadai-yoyaku/config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    collection do
      get 'search'
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  #get 'reservations/new'
  #get 'reservations/show'
  get 'pusts/index'
  get 'users/index'
  get 'posts/index'
  get "users/show" => "users#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :posts, param: :id
  resources :users#, only: :show
  post 'posts/new'

  resources :posts do
    resources :reservations
  end

  post 'reservations/back'
  post 'reservations/complete'

end

rails-kadai-yoyaku/app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post

  with_options presence: true do
    validates :start_date
    validates :end_date
    validates :number_of_reservations, numericality: {greater_than_or_equal_to: 1}
  end

  validate :start_end_check
  def start_end_check
    if self.start_date.nil?
    elsif self.end_date.nil?
    else
      errors.add(:end_date) unless
      self.start_date < self.end_date
    end
  end

  validate :date_before_start
  def date_before_start
    if self.start_date.nil?
    else
      errors.add(:start_date) if
      start_date < Date.today
    end
  end
end

rails-kadai-yoyaku/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservation = Reservation.all
  end

  def new
    @reservation = Reservation.new(reservation_params)
    @post = Post.find(params[:post_id])
    if @reservation.invalid?
      render :show
    end
  end

  def create
    @reservation = current_user.reservations.create(reservation_params)
  end

  def show
    @post = Post.find(params[:id])
    @reservation = Reservation.new
  end

  def back
    @reservation = Reservation.new(reservation_params)
    @post = Post.find(params[:format])
		render :show
	end

  def complete
	  current_user.reservations.create!(reservation_params)
    @post = Post.find(params[:format])
    @reservation = Reservation.new(reservation_params)
	end

  def edit
  end

  def update
  end

  def destroy
    Reservation.find_by(id: params[:id],post_id: params[:post_id]).destroy
    flash[:notice] = "予約を削除しました"
    redirect_to :post_reservations
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :number_of_reservations, :post_id)
  end

end

rails-kadai-yoyaku/app/helpers/reservations_helper.rb
module ReservationsHelper
end

rails-kadai-yoyaku/app/views/reservations/complete.html.erb
<h1>ご予約ありがとうございました。</h1>

<dl>
  <dt>予約した部屋</dt>
	<dd><%= @post.room_name %></dd>
	<dt>開始日</dt>
	<dd><%= @reservation.start_date.to_s(:ja) %></dd>
	<dt>終了日</dt>
	<dd><%= @reservation.end_date.to_s(:ja) %></dd>
  <dt>使用日数</dt>
	<dd>
    <% past_seconds = @reservation.end_date-@reservation.start_date %>
    <%= past_days = (past_seconds / 1.days).floor %>日
  </dd>
	<dt>人数</dt>
	<dd><%= @reservation.number_of_reservations %>人</dd>
  <dt>合計金額</dt>
	<dd><%= @post.room_price*past_days*@reservation.number_of_reservations %>円</dd>
</dl>

rails-kadai-yoyaku/app/views/reservations/index.html.erb
<h3>予約済みルーム一覧</h3>

<table>
    <thead>
      <tr>
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>人数</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
        <th>削除</th>
      </tr>
    </thead>

    <tbody>
      <% @reservation.each do |reservation| %>
        <tr>
          <td><%= link_to image_tag(reservation.post.room_image.url, :size =>'250x150'), post_reservation_path(reservation.id, reservation.post.id), method: :get %></td>
          <td><%= link_to reservation.post.room_name, post_reservation_path(reservation.id, reservation.post.id), method: :get %></td>
          <td><%= reservation.post.room_introduction %></td>
          <td><%= reservation.number_of_reservations %></td>
          <td>¥ <% past_seconds = reservation.end_date-reservation.start_date %>
                <% past_days = (past_seconds / 1.days).floor %>
                <%= reservation.post.room_price*past_days*reservation.number_of_reservations %></td>
          <td><%= reservation.start_date.to_s(:ja) %></td>
          <td><%= reservation.end_date.to_s(:ja) %></td>
          <td><%= reservation.created_at.to_s(:datetime_jp) %></td>
          <td><%= link_to "削除", post_reservation_path(reservation.post.id, reservation.id), method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

rails-kadai-yoyaku/app/views/reservations/new.html.erb
<h1>予約フォーム</h1>
¥ <%= @post.room_price %> / 日
<dl>
	<dt>開始日</dt>
	<dd><%= @reservation.start_date.to_s(:ja) %></dd>
	<dt>終了日</dt>
	<dd><%= @reservation.end_date.to_s(:ja) %></dd>
  <dt>使用日数</dt>
	<dd>
    <% past_seconds = @reservation.end_date-@reservation.start_date %>
    <%= past_days = (past_seconds / 1.days).floor %>日
  </dd>
	<dt>人数</dt>
	<dd><%= @reservation.number_of_reservations %>人</dd>
  <dt>合計金額</dt>
	<dd><%= @post.room_price*past_days*@reservation.number_of_reservations %>円</dd>
</dl>

<h6>上記内容でよろしければ「予約を確定」を押してください</h6>

<%= form_for [@post, @post.reservations.new], method: :post, url: reservations_complete_path(@post.id) do |f| %>
  <%= f.hidden_field :post_id, value: @post.id %>

  <%= f.hidden_field :start_date, :value => @reservation.start_date %>

  <%= f.hidden_field :end_date, :value =>  @reservation.end_date %>

  <%= f.hidden_field :number_of_reservations, :value =>  @reservation.number_of_reservations %>

  <%= f.submit "予約を確定", class: "btn btn-danger btn-wide" %>

<% end %>

<%= form_for [@post, @post.reservations.new], method: :post, url: reservations_back_path(@post.id) do |f| %>
  <%= f.hidden_field :post_id, value: @post.id %>

  <%= f.hidden_field :start_date, :value => @reservation.start_date %>

  <%= f.hidden_field :end_date, :value =>  @reservation.end_date %>

  <%= f.hidden_field :number_of_reservations, :value =>  @reservation.number_of_reservations %>

  <%= f.submit "ルーム詳細に戻る", class: "btn btn-danger btn-wide" %>

<% end %>

rails-kadai-yoyaku/app/views/reservations/show.html.erb
<h3>予約フォーム</h3>

<%= image_tag(@post.room_image.url, :size =>'400x300') %><br>
<%= @post.room_name %><br>
<%= @post.room_address %><br>
<%= @post.room_introduction %><br>
¥ <%= @post.room_price %> / 日<br>

<%= form_for @reservation, method: :get, url: new_post_reservation_path(@post) do |f| %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <div class="col-md-6">
    <label>開始日</label>
    <%= f.date_field :start_date, :class => 'datepicker' %>
  </div>

  <div class="col-md-6">
    <label>終了日</label>
    <%= f.date_field :end_date, :class => 'datepicker' %>
  </div>

  <div class="col-md-6">
    <label>人数</label>
    <%= f.number_field :number_of_reservations, min: 0, :class => 'datepicker' %>
  </div>

  <% if user_signed_in? %>
    <%= f.submit "予約する", class: "btn btn-danger btn-wide" %>
  <% end %>

<% end %>

<% unless user_signed_in? %>
  <%= button_to "ログイン", new_user_session_path, class: 'login-button' %>
<% end %>